create user peliculas IDENTIFIED by peliculas;
Grant connect, dba, RESOURCE to peliculas;
/*vamos a crear tablas*/

CREATE TABLE USUARIO (
dni varchar2(9) NOT NULL PRIMARY KEY,
nombre varchar2(25) not null,
contraseña varchar2(30) not null,
apellido varchar2(50),
edad number(2) not null
);
/*VAMOS A CREAR LA TABLA DE TARJETAS DEL USUARIO*/
CREATE TABLE TARJETAS(
NUMERO NUMBER(10) PRIMARY KEY NOT NULL,
CANTIDAD number(7),
DNIUSUARIO VARCHAR2(9) REFERENCES USUARIO(dni)
);
/*Crearemos la tabla peliculas*/
CREATE TABLE PELICULAS (
CODIGO NUMBER(9) NOT NULL PRIMARY KEY,
TITULO varchar2(50) not null,
GENERO varchar2(50),
DURACION NUMBER(3),
edad number(2) not null,
PRECIO NUMBER(6) NOT NULL
);
/*CREAR TABLA COMPRAS*/
CREATE TABLE COMPRAS(
CODCOMPRA NUMBER(5) PRIMARY KEY NOT NULL,
FECHA DATE NOT NULL,
TOTALCOMPA NUMBER(6),
DNIUSUARIO VARCHAR2(9) REFERENCES USUARIO(dni)
);
/*CREAR LINEA DE COMRAS*/
CREATE TABLE Lineas(
CODLINEA NUMBER(5) PRIMARY KEY NOT NULL,
CODCOMPRA number(5) REFERENCES COMPRAS(CODCOMPRA),
CODPELICULA NUMBER(9) NOT NULL REFERENCES PELICULAS(CODIGO),
CANTIDAD number(6),
PRECIOTOTAL NUMBER(6)
);
/*********Insertar datos en la tabla*******/
